### ISSUE TITLE
دادگان در این قسمت شبیه به داده سازی است

### ISSUE THREAD

**Issue by alikhabazian** [Choraz/videos#1]
اول اینکه بسیار خوشحالم که کسایی هستن که اقتصاد را به زبان مفهوم برای همه میگن چون من خودم خیلی از مفاهیم را اینحا یاد گرفتم
و خیلی ممنون که سعی کردین این کار ره به صورت opensource انجام بدین این واقعا باعث پبشرفت همگانی خواهد شد
اما مشکلی که وجود دارد این است که دادگانی که استفاده شده ( احتمالا از جایی برداشت شده با نوشته شده یا محاسبه شده)
اگر محاسبه شده آنها هم باید در اینحا وحود داشته باشند
و اگر از منبعی میاند بهتر است موقع استفاده در کد اشاره به لینک آنها در کامنت ها شده باشد
و خوشحال میشم اگر نیاز به نیرو باز هم داشتین کمک کننده باشم چون به اقتصاد نیز علاقه مند هستم

**Comment by m-amin-alavian** [comment]
سلام!
خیلی از لطف شما متشکرم.
در ویدیوی شماره‌ی ۱ سال ۱۴۰۲ که مورد اشاره‌ی شماست از دو مجموعه‌ی داده استفاده شده. برای داده‌های بین المللی، فایل [part1_international.ipynb](https://github.com/Choraz/videos/blob/main/1402/1_maslow/part1_international.ipynb) از یک فایل اکسل که بر روی سایت www.ers.usda.gov بوده استفاده کردیم که لینکش در خود داده هست و بخش اول کد به دانلود و مرتب کردن این فایل اختصاص داره.
برای بخش دوم، داده‌های مربوط به ایران که برگرفته از بودجه‌ی خانواره، از پکیج [hbsir](https://github.com/Iran-Open-Data/HBSIR) استفاده کردیم که به صورت منبع باز منتشر شده و در دسترسه.
حتما همه‌ی انواع مشارکت‌های شما مورد استقباله! از ایده برای ویدیو‌های داده محور تا ارتقاء کدهای موجود و هر چیزی که برای خودتون جالب باشه.
